CREATE TABLE `test`.`METAL_MARKET` (
  `id` INT NOT NULL,
  `Outcome` VARCHAR(45) NULL,
  `Message` VARCHAR(45) NULL,
  `Identity` VARCHAR(45) NULL,
  `Delay` DOUBLE NULL,
  `Name` VARCHAR(45) NULL,
  `Symbol` VARCHAR(45) NULL,
  `Unit` VARCHAR(45) NULL,
  `QuoteType` VARCHAR(45) NULL,
  `Currency` VARCHAR(45) NULL,
  `Date` VARCHAR(45) NULL,
  `Time` VARCHAR(45) NULL,
  `Bid` DOUBLE NULL,
  `Mid` DOUBLE NULL,
  `Ask` DOUBLE NULL,
  `Spread` DOUBLE NULL,
  `Source` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));

ALTER TABLE `test`.`METAL_MARKET`
CHANGE COLUMN `id` `id` INT(11) NOT NULL AUTO_INCREMENT ;

ALTER TABLE `test`.`METAL_MARKET`
CHANGE COLUMN `Source` `Source` VARCHAR(256) NULL DEFAULT NULL ;

